allowBuilds:
  '@ipshipyard/node-datachannel': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  iso-constants: true
  lefthook: true
  node-datachannel: true
  protobufjs: true
  sharp: true
onlyBuiltDependencies: '@ipshipyard/node-datachannel'
